// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	dependencystrategies "github.com/mertozler/internal/checker/dependencystrategies"
	mock "github.com/stretchr/testify/mock"

	models "github.com/mertozler/internal/models"
)

// Checker is an autogenerated mock type for the Checker type
type Checker struct {
	mock.Mock
}

// Check provides a mock function with given fields: strategyType, url
func (_m *Checker) Check(strategyType string, url string) (*models.OutDatedResponse, error) {
	ret := _m.Called(strategyType, url)

	var r0 *models.OutDatedResponse
	if rf, ok := ret.Get(0).(func(string, string) *models.OutDatedResponse); ok {
		r0 = rf(strategyType, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OutDatedResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(strategyType, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterStrategy provides a mock function with given fields: name, strategy
func (_m *Checker) RegisterStrategy(name string, strategy dependencystrategies.DependencyStrategy) {
	_m.Called(name, strategy)
}

type mockConstructorTestingTNewChecker interface {
	mock.TestingT
	Cleanup(func())
}

// NewChecker creates a new instance of Checker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewChecker(t mockConstructorTestingTNewChecker) *Checker {
	mock := &Checker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
