// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "github.com/mertozler/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// DependencyStrategy is an autogenerated mock type for the DependencyStrategy type
type DependencyStrategy struct {
	mock.Mock
}

// Check provides a mock function with given fields: url
func (_m *DependencyStrategy) Check(url string) (*models.OutDatedResponse, error) {
	ret := _m.Called(url)

	var r0 *models.OutDatedResponse
	if rf, ok := ret.Get(0).(func(string) *models.OutDatedResponse); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OutDatedResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDependencyStrategy interface {
	mock.TestingT
	Cleanup(func())
}

// NewDependencyStrategy creates a new instance of DependencyStrategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDependencyStrategy(t mockConstructorTestingTNewDependencyStrategy) *DependencyStrategy {
	mock := &DependencyStrategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
